name: Monitor VUCE

on:
  schedule:
    - cron: "*/10 * * * *"   # cada 10 minutos
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar monitor
        run: python main.py